/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiInternalWeeklyReportRouteImport } from './routes/api/internal/weekly-report'
import { Route as ApiInternalRemindersRouteImport } from './routes/api/internal/reminders'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalWeeklyReportRoute = ApiInternalWeeklyReportRouteImport.update({
  id: '/api/internal/weekly-report',
  path: '/api/internal/weekly-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalRemindersRoute = ApiInternalRemindersRouteImport.update({
  id: '/api/internal/reminders',
  path: '/api/internal/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/internal/reminders': typeof ApiInternalRemindersRoute
  '/api/internal/weekly-report': typeof ApiInternalWeeklyReportRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/internal/reminders': typeof ApiInternalRemindersRoute
  '/api/internal/weekly-report': typeof ApiInternalWeeklyReportRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/internal/reminders': typeof ApiInternalRemindersRoute
  '/api/internal/weekly-report': typeof ApiInternalWeeklyReportRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/internal/reminders'
    | '/api/internal/weekly-report'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/internal/reminders'
    | '/api/internal/weekly-report'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/api/internal/reminders'
    | '/api/internal/weekly-report'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiInternalRemindersRoute: typeof ApiInternalRemindersRoute
  ApiInternalWeeklyReportRoute: typeof ApiInternalWeeklyReportRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/weekly-report': {
      id: '/api/internal/weekly-report'
      path: '/api/internal/weekly-report'
      fullPath: '/api/internal/weekly-report'
      preLoaderRoute: typeof ApiInternalWeeklyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/reminders': {
      id: '/api/internal/reminders'
      path: '/api/internal/reminders'
      fullPath: '/api/internal/reminders'
      preLoaderRoute: typeof ApiInternalRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiInternalRemindersRoute: ApiInternalRemindersRoute,
  ApiInternalWeeklyReportRoute: ApiInternalWeeklyReportRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
